import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatDateAR } from './dateUtils';
import { CURRENCIES } from './constants';

// تحويل الصورة إلى base64
const getImageAsBase64 = async (imagePath) => {
  try {
    const response = await fetch(imagePath);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error('Error loading image:', error);
    return null;
  }
};

// ترجمات للغات المختلفة - محدثة ومصححة
const getTranslations = (lang = 'ar') => {
  const translations = {
    ar: {
      invoiceIn: 'فاتورة وارد',
      invoiceOut: 'فاتورة صادر',
      date: 'التاريخ',
      invoiceNumber: 'رقم الفاتورة',
      description: 'البيان',
      amount: 'المبلغ',
      category: 'التصنيف',
      vendor: 'المورد',
      customer: 'العميل',
      status: 'الحالة',
      signature: 'التوقيع',
      stamp: 'الختم',
      footer: 'تم إنشاء هذه الفاتورة تلقائياً من نظام إبراهيم للمحاسبة',
      itemName: 'اسم المنتج',
      quantity: 'الكمية',
      unitPrice: 'سعر الوحدة',
      total: 'الإجمالي',
      unit: 'الوحدة',
      items: 'المنتجات',
      totalAmount: 'المبلغ الإجمالي',
      reportDate: 'تاريخ التقرير',
      reportFooter: 'تم إنشاء هذا التقرير تلقائياً من نظام إبراهيم للمحاسبة'
    },
    en: {
      invoiceIn: 'Invoice In',
      invoiceOut: 'Invoice Out',
      date: 'Date',
      invoiceNumber: 'Invoice Number',
      description: 'Description',
      amount: 'Amount',
      category: 'Category',
      vendor: 'Vendor',
      customer: 'Customer',
      status: 'Status',
      signature: 'Signature',
      stamp: 'Stamp',
      footer: 'This invoice was automatically generated by Ibrahim Accounting System',
      itemName: 'Item Name',
      quantity: 'Quantity',
      unitPrice: 'Unit Price',
      total: 'Total',
      unit: 'Unit',
      items: 'Items',
      totalAmount: 'Total Amount',
      reportDate: 'Report Date',
      reportFooter: 'This report was automatically generated by Ibrahim Accounting System'
    },
    tr: {
      invoiceIn: 'Gelen Fatura',
      invoiceOut: 'Giden Fatura',
      date: 'Tarih',
      invoiceNumber: 'Fatura Numarası',
      description: 'Açıklama',
      amount: 'Tutar',
      category: 'Kategori',
      vendor: 'Tedarikçi',
      customer: 'Müşteri',
      status: 'Durum',
      signature: 'İmza',
      stamp: 'Mühür',
      footer: 'Bu fatura İbrahim Muhasebe Sistemi tarafından otomatik olarak oluşturulmuştur',
      itemName: 'Ürün Adı',
      quantity: 'Miktar',
      unitPrice: 'Birim Fiyat',
      total: 'Toplam',
      unit: 'Birim',
      items: 'Ürünler',
      totalAmount: 'Toplam Tutar',
      reportDate: 'Rapor Tarihi',
      reportFooter: 'Bu rapor İbrahim Muhasebe Sistemi tarafından otomatik olarak oluşturulmuştur'
    }
  };
  return translations[lang] || translations.ar;
};

// إنشاء PDF للفاتورة مع دعم لغات متعددة وعناصر - محدث مع إصلاح مشاكل اللغة
export const generateInvoicePDF = async (invoice, type, tenantName, logoPath = '/logo.png', language = 'ar', invoiceItems = []) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const t = getTranslations(language);
  const isRTL = language === 'ar';
  
  // إضافة دعم الخطوط العربية
  if (isRTL) {
    // استخدام Unicode fonts للعربية
    doc.setLanguage('ar');
  }
  
  // تحميل الشعار
  let logoBase64 = null;
  try {
    logoBase64 = await getImageAsBase64(logoPath);
  } catch (error) {
    console.error('Logo not found, continuing without logo');
  }

  // رأس الصفحة
  let startY = 20;

  // الشعار في الأعلى
  if (logoBase64) {
    try {
      const logoSize = 30;
      const logoX = isRTL ? pageWidth - 25 : 20;
      doc.addImage(logoBase64, 'PNG', logoX, 10, logoSize, logoSize);
    } catch (error) {
      console.error('Error adding logo:', error);
    }
  }

  // العنوان الرئيسي
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  const title = type === 'in' ? t.invoiceIn : t.invoiceOut;
  const titleWidth = doc.getTextWidth(title);
  const titleX = isRTL ? pageWidth - 20 - titleWidth : 20;
  doc.text(title, titleX, 25);
  
  // اسم المتجر
  if (tenantName) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    const nameWidth = doc.getTextWidth(tenantName);
    const nameX = isRTL ? pageWidth - 20 - nameWidth : 20;
    doc.text(tenantName, nameX, 32);
  }

  startY = 40;

  // معلومات الفاتورة - استخدام جدول منسق
  const headerData = [];
  
  if (invoice.invoice_number || invoice.id) {
    headerData.push([
      t.invoiceNumber + ':',
      invoice.invoice_number || invoice.id?.substring(0, 8) || '-'
    ]);
  }
  
  if (invoice.date) {
    const formattedDate = formatDateAR(invoice.date, { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    headerData.push([t.date + ':', formattedDate]);
  }

  if (invoice.partner_name) {
    headerData.push([
      (type === 'in' ? t.vendor : t.customer) + ':',
      invoice.partner_name
    ]);
  }

  if (invoice.category) {
    headerData.push([t.category + ':', invoice.category]);
  }

  if (invoice.status) {
    headerData.push([t.status + ':', invoice.status]);
  }

  // جدول معلومات الفاتورة الأساسية
  if (headerData.length > 0) {
    autoTable(doc, {
      startY: startY,
      head: [[isRTL ? 'المعلومة' : 'Information', isRTL ? 'القيمة' : 'Value']],
      body: headerData,
      theme: 'plain',
      headStyles: { 
        fillColor: [255, 140, 0], 
        textColor: 255, 
        fontStyle: 'bold',
        halign: 'center'
      },
      styles: { 
        fontSize: 10, 
        halign: isRTL ? 'right' : 'left',
        font: 'helvetica',
        fontStyle: 'normal',
        cellPadding: 5
      },
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: isRTL ? 70 : 50, fontStyle: 'bold' },
        1: { cellWidth: 'auto', halign: isRTL ? 'right' : 'left' }
      },
      didParseCell: function(data) {
        if (isRTL && data.row.index >= 0) {
          data.cell.styles.halign = 'right';
        }
      }
    });

    startY = doc.lastAutoTable.finalY + 10;
  }

  // جدول البيان/الوصف
  if (invoice.description) {
    autoTable(doc, {
      startY: startY,
      head: [[t.description]],
      body: [[invoice.description]],
      theme: 'plain',
      headStyles: { 
        fillColor: [245, 245, 245], 
        textColor: 0, 
        fontStyle: 'bold',
        halign: 'center'
      },
      styles: { 
        fontSize: 11, 
        halign: isRTL ? 'right' : 'left',
        font: 'helvetica',
        cellPadding: 5
      },
      margin: { left: 20, right: 20 }
    });
    startY = doc.lastAutoTable.finalY + 10;
  }

  // جدول العناصر (إن وجدت)
  if (invoiceItems && invoiceItems.length > 0) {
    const itemsTableBody = invoiceItems.map(item => [
      item.name || item.item_name || '-',
      String(item.quantity || item.qty || 0),
      String(item.unit || '-'),
      parseFloat(item.unit_price || item.price || 0).toLocaleString('ar-EG', { minimumFractionDigits: 2 }),
      parseFloat(item.total || (item.quantity || 0) * (item.unit_price || item.price || 0)).toLocaleString('ar-EG', { minimumFractionDigits: 2 })
    ]);

    autoTable(doc, {
      startY: startY,
      head: [[
        t.itemName,
        t.quantity,
        t.unit,
        t.unitPrice,
        t.total
      ]],
      body: itemsTableBody,
      theme: 'striped',
      headStyles: { 
        fillColor: [255, 140, 0], 
        textColor: 255, 
        fontStyle: 'bold',
        halign: 'center'
      },
      styles: { 
        fontSize: 9, 
        halign: isRTL ? 'right' : 'left',
        font: 'helvetica',
        cellPadding: 3
      },
      margin: { left: 20, right: 20 },
      columnStyles: {
        0: { cellWidth: isRTL ? 60 : 70 },
        1: { halign: 'center', cellWidth: 25 },
        2: { halign: 'center', cellWidth: 25 },
        3: { halign: 'right', cellWidth: 30 },
        4: { halign: 'right', cellWidth: 30, fontStyle: 'bold' }
      }
    });
    startY = doc.lastAutoTable.finalY + 10;
  }

  // المبلغ الإجمالي
  const currencyInfo = CURRENCIES[invoice.currency || 'TRY'] || CURRENCIES.TRY;
  const amount = parseFloat(invoice.amount || 0);
  const formattedAmount = amount.toLocaleString('ar-EG', { minimumFractionDigits: 2 });
  
  autoTable(doc, {
    startY: startY,
    body: [[
      t.totalAmount + ':',
      currencyInfo.symbol + ' ' + formattedAmount + ' (' + currencyInfo.code + ')'
    ]],
    theme: 'plain',
    styles: { 
      fontSize: 12, 
      halign: isRTL ? 'right' : 'left',
      font: 'helvetica',
      fontStyle: 'bold',
      cellPadding: 5
    },
    margin: { left: 20, right: 20 },
    columnStyles: {
      0: { cellWidth: isRTL ? 70 : 60, fontStyle: 'bold' },
      1: { cellWidth: 'auto', halign: isRTL ? 'right' : 'left', fontStyle: 'bold', textColor: [255, 140, 0] }
    }
  });

  // التذييل
  const footerY = pageHeight - 20;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(128, 128, 128);
  const footerText = t.footer;
  const footerWidth = doc.getTextWidth(footerText);
  const footerX = isRTL ? pageWidth - 20 - footerWidth : 20;
  doc.text(footerText, footerX, footerY);

  // إضافة رقم الصفحة
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  const pageNum = doc.internal.pages.length - 1;
  const pageText = language === 'ar' ? `صفحة ${pageNum}` : language === 'tr' ? `Sayfa ${pageNum}` : `Page ${pageNum}`;
  const pageWidth_text = doc.getTextWidth(pageText);
  const pageX = isRTL ? 20 : pageWidth - 20 - pageWidth_text;
  doc.text(pageText, pageX, footerY);

  return doc;
};

// إنشاء PDF للتقرير مع دعم لغات متعددة - محدث
export const generateReportPDF = async (title, data, columns, tenantName, logoPath = '/logo.png', language = 'ar') => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
    compress: true
  });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const t = getTranslations(language);
  const isRTL = language === 'ar';

  if (isRTL) {
    doc.setLanguage('ar');
  }

  let startY = 20;

  // الشعار
  let logoBase64 = null;
  try {
    logoBase64 = await getImageAsBase64(logoPath);
    if (logoBase64) {
      const logoSize = 25;
      const logoX = isRTL ? pageWidth - 20 : 20;
      doc.addImage(logoBase64, 'PNG', logoX, 10, logoSize, logoSize);
    }
  } catch (error) {
    console.error('Logo not found');
  }

  // العنوان
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  const titleWidth = doc.getTextWidth(title);
  const titleX = isRTL ? pageWidth - 20 - titleWidth : 20;
  doc.text(title, titleX, 25);

  // اسم المتجر
  if (tenantName) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    const nameWidth = doc.getTextWidth(tenantName);
    const nameX = isRTL ? pageWidth - 20 - nameWidth : 20;
    doc.text(tenantName, nameX, 32);
  }

  // تاريخ التقرير
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  const reportDate = t.reportDate + ': ' + formatDateAR(new Date(), {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const dateWidth = doc.getTextWidth(reportDate);
  const dateX = isRTL ? pageWidth - 20 - dateWidth : 20;
  doc.text(reportDate, dateX, 38);

  startY = 45;

  // تحويل الأعمدة والبيانات
  const tableHead = columns.map(col => 
    typeof col === 'string' ? col : (col.header || col.label || '')
  );

  const tableBody = data.map(row => 
    columns.map(col => {
      const accessor = typeof col === 'string' ? col : (col.accessor || col.key || '');
      if (typeof accessor === 'function') {
        return String(accessor(row) || '-');
      }
      return String(row[accessor] || '-');
    })
  );

  // جدول البيانات
  autoTable(doc, {
    startY: startY,
    head: [tableHead],
    body: tableBody,
    theme: 'striped',
    headStyles: { 
      fillColor: [255, 140, 0], 
      textColor: 255, 
      fontStyle: 'bold',
      halign: 'center'
    },
    styles: { 
      fontSize: 8, 
      halign: isRTL ? 'right' : 'left',
      font: 'helvetica',
      cellPadding: 3,
      overflow: 'linebreak',
      cellWidth: 'wrap'
    },
    margin: { left: 10, right: 10 },
    didParseCell: function(data) {
      if (isRTL) {
        data.cell.styles.halign = 'right';
      }
    }
  });

  // التذييل
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(128, 128, 128);
  const footerText = t.reportFooter;
  const footerWidth = doc.getTextWidth(footerText);
  const footerX = isRTL ? pageWidth - 10 - footerWidth : 10;
  doc.text(footerText, footerX, footerY);

  return doc;
};

// تصدير PDF
export const exportInvoicePDF = async (invoice, type, tenantName, logoPath, language = 'ar', invoiceItems = []) => {
  const doc = await generateInvoicePDF(invoice, type, tenantName, logoPath, language, invoiceItems);
  const fileName = `${type === 'in' ? 'invoice_in' : 'invoice_out'}_${invoice.invoice_number || invoice.id?.substring(0, 8) || Date.now()}.pdf`;
  doc.save(fileName);
};

export const exportReportPDF = async (title, data, columns, tenantName, logoPath, language = 'ar') => {
  const doc = await generateReportPDF(title, data, columns, tenantName, logoPath, language);
  const fileName = `report_${Date.now()}.pdf`;
  doc.save(fileName);
};

// طباعة PDF (فتح نافذة الطباعة)
export const printInvoice = async (invoice, type, tenantName, logoPath = '/logo.png', language = 'ar', invoiceItems = []) => {
  const doc = await generateInvoicePDF(invoice, type, tenantName, logoPath, language, invoiceItems);
  // إنشاء blob من PDF
  const pdfBlob = doc.output('blob');
  const pdfUrl = URL.createObjectURL(pdfBlob);
  
  // فتح PDF في نافذة جديدة وطباعته
  const printWindow = window.open(pdfUrl, '_blank');
  if (printWindow) {
    printWindow.onload = () => {
      printWindow.print();
    };
  }
  
  // تنظيف URL بعد الطباعة
  setTimeout(() => {
    URL.revokeObjectURL(pdfUrl);
  }, 1000);
};